services:
  app:
    build: .
    container_name: ideaflow_app
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USERNAME=postgres
      - DB_PASSWORD=1234
      - DB_NAME=ideaflow_db
      - JWT_SECRET=your-super-secret-jwt-key-for-development-123
    networks:
      - ideaflow_network
    depends_on:
      postgres:
        condition: service_healthy
    command: node dist/main

  postgres:
    image: postgres:15
    container_name: ideaflow_db
    environment:
      POSTGRES_DB: ideaflow_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./infrastructure/database/init:/docker-entrypoint-initdb.d
    networks:
      - ideaflow_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4
    container_name: ideaflow_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@ideaflow.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8080:80"
    networks:
      - ideaflow_network
    depends_on:
      - postgres

volumes:
  postgres_data:

networks:
  ideaflow_network:
    driver: bridge